name: build
on:
  push:
  schedule:
    - cron: '0 1 * * 6' # weekly check that it still works
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run the Gradle test task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
